development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: text_app_development

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: text_app_production
  connection_pool_size: 5
